---
- hosts: all
  tasks:
  - name: Base configuration
    include_role:
      name: base
  - name: Configure IDM client
    include_role:
      name: ipaclient
  - name: install jupyter
    include_role:
      name: jupyter
...
