- name: install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - epel-release
  - bash-completion
  - python3-virtualenv
  - npm
  - '@development'
  - vim-enhanced
  - vim-pathogen
  - tree
  - wget
  - krb5-pkinit
- name: install jupyterhub and jupyterlab
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: /opt/jupyter
  loop:
  - jupyterhub
  - jupyterhub-systemdspawner
  - jupyterlab
  - psycopg2-binary
  - powerline-status
- name: install configurable proxy
  npm:
    name: configurable-http-proxy
    path: /opt/jupyter/lib
    state: present
- name: create symlink to npm binaries
  file:
    src: "/opt/jupyter/{{ item.filename }}"
    dest: "/opt/jupyter/{{ item.linkname }}"
    state: link
  loop:
  - { filename: 'lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy', linkname: 'bin/configurable-http-proxy' }
