---
- name: install firewalld
  dnf:
    name: firewalld
    state: present
- name: run firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
- name: configure firewalld
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  loop:
  - http
  - https
...
