---
- name: Set selinux enforcing
  selinux:
    policy: targeted
    state: enforcing
  register: result
- name: Mark to relabel
  file:
    path: /.autorelabel
    state: touch
  when: result.changed
- name: Reboot to relabel
  reboot:
  when: result.changed
- name: wait for reboot
  wait_for_connection:
  when: result.changed
- name: allow httpd connect network
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
    #- name: check loaded selinux policies
    #  command:
    #    argv:
    #    - "semodule"
    #    - "-l"
    #  register: selinuxmodules
    #  check_mode: no
    #  changed_when: False
    #- name: copy init2nnp policy
    #  copy:
    #    dest: /tmp/init2nnp.pp
    #    mode: 0600
    #    owner: root
    #    src: init2nnp.pp
    #  when: "selinuxmodules.stdout.find('init2nnp') == -1"
    #- name: load init2nnp policy
    #  command:
    #    argv:
    #    - "semodule"
    #    - "-i"
    #    - "/tmp/init2nnp.pp"
    #  when: "selinuxmodules.stdout.find('init2nnp') == -1"
...
